//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelebeProqrami
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbTelebelerEntities : DbContext
    {
        public dbTelebelerEntities()
            : base("name=dbTelebelerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Dersler> TBL_Dersler { get; set; }
        public virtual DbSet<TBL_Qeydler> TBL_Qeydler { get; set; }
        public virtual DbSet<TBL_Telebeler> TBL_Telebeler { get; set; }
        public virtual DbSet<TBL_Klublar> TBL_Klublar { get; set; }
    
        public virtual ObjectResult<TelebeQeydleri_Result> TelebeQeydleri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelebeQeydleri_Result>("TelebeQeydleri");
        }
    }
}
