//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelebeProqrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Klublar
    {
        public int KlubID { get; set; }
        public string KlubAD { get; set; }
    }
}
