//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelebeProqrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Qeydler
    {
        public int QeydID { get; set; }
        public Nullable<int> Telebe { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<short> Imtahan1 { get; set; }
        public Nullable<short> Imtahan2 { get; set; }
        public Nullable<short> Imtahan3 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Veziyyet { get; set; }
    
        public virtual TBL_Dersler TBL_Dersler { get; set; }
        public virtual TBL_Telebeler TBL_Telebeler { get; set; }
    }
}
